baseURL: https://drew.shoes
SectionPagesMenu: main
languageCode: en-us
title: drew dot shoes
author:
  name: Drew Schuster
enableEmoji: true
enableRobotsTXT: true
theme: PaperMod
markup:
  goldmark:
    renderer:
      unsafe: true
frontmatter:
  date:
  - publishDate
  - :default
menu:
  main:
  - identifier: rss
    name: RSS
    url: /feed.xml
params:
  author: Drew Schuster
  showReadingTime: true
  disable_share: true
  background_color_class: bg-dark-gray
  defaultTheme: dark # dark, light
  disableThemeToggle: true
  ShowFullTextinRSS: true
  ShowShareButtons: false
  ShowCodeCopyButtons: true
  homeInfoParams:
    Content: >
      Let me tell you about my boat.
  socialIcons:
    - name: mastodon
      url: https://xoxo.zone/@nuncamind
    - name: twitter
      url: "https://twitter.com/nuncamind"
    - name: github
      url: "https://github.com/dtschust"
    - name: rss
      url: "/feed.xml"
  analytics:
    google:
      SiteVerificationTag: "G-48YQMQSZGS"
outputFormats:
  RSS:
    baseName: feed