baseURL: https://drew.shoes
SectionPagesMenu: main
languageCode: en-us
title: drew dot shoes
author:
  name: Drew Schuster
enableEmoji: true
enableRobotsTXT: true
theme: PaperMod
markup:
  goldmark:
    renderer:
      unsafe: true
frontmatter:
  date:
  - publishDate
  - :default
menu:
  main:
  - identifier: rss
    name: RSS
    title: rss
    url: /feed.xml
params:
  author: Drew Schuster
  showReadingTime: true
  disable_share: true
  background_color_class: bg-dark-gray
  defaultTheme: dark # dark, light
  disableThemeToggle: true
  ShowFullTextinRSS: true
  ShowShareButtons: false
  ShowCodeCopyButtons: true
  homeInfoParams:
    Content: >
      ![photo of me in front of the Parthenon](/images/home.jpg)
      <p align="center">Let me tell you about my boat</p>
  analytics:
    google:
      SiteVerificationTag: "G-48YQMQSZGS"
outputFormats:
  RSS:
    baseName: feed